/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bqt_hellofromc_MyNativeMethods */

#ifndef _Included_com_bqt_hellofromc_MyNativeMethods
#define _Included_com_bqt_hellofromc_MyNativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bqt_hellofromc_MyNativeMethods
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bqt_hellofromc_MyNativeMethods_helloFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_bqt_hellofromc_MyNativeMethods
 * Method:    passwordFromC
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_bqt_hellofromc_MyNativeMethods_passwordFromC
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
